### ISSUE TITLE
Mismatch Between Shapes of Kernels in Paper and Code

### ISSUE THREAD

**Issue by mistermoutan** [M3DV/ACSConv#11]
Hello,

Though the shape of the kernels which is supposed to map axial features is said to be of dimensions _(Co,Ci,k,k,1)_ in the paper, the implementation` weight_a = weight[0 : acs_kernel_split[0]].unsqueeze(2)` makes it so that this weight will be _(Co,Ci,1,k,k)_ in dimensions. So only `weight_c` is correct as in the paper since `weight_s` is also not being unsqueezed in the proper dimension. 

I do not believe this is of  importance for the experiments you have conducted but, for my experimental purposes I need to match the kernels partitions to views of 2D slices so I notices this when I went to make sure of what is happening.

**Comment by duducheng** [comment]
Hi @mistermoutan,

Thank you for figuring it out! 

We simply regard the `_a`, `_c`, and `_s` as symmetric subscript in the code.

We will add a sentence in the code.
