### ISSUE TITLE
Raise NotImplementedError

### ISSUE THREAD

**Issue by royzhang12** [M3DV/ACSConv#13]
Hi, I am trying to go through the train_3d experiment. I found that in the base_convert.py when calling the convert_module, it will raise NotImplementedError no matter what input module you give. This is quite confusing as it terminates the program without any expected output. Would you mind to tell me how to solve that?

**Comment by duducheng** [comment]
Hi @royzhang12 ,

The `base_convert.py` provides a base class only. Please use a specific convertor, e.g., `ACSConverter`. You can also check our example code. 

Jiancheng

**Comment by royzhang12** [comment]
Thank you. It solved my problem perfectly.
