### ISSUE TITLE
Any reason for `torch<=1.10.0` dependency?

### ISSUE THREAD

**Issue by sarthakpati** [M3DV/ACSConv#18]
Thanks for the amazing work on this. Is there a specific reason for this dependency requirement or has this not been evaluated for newer releases?

Cheers,
Sarthak

**Comment by seanywang0408** [comment]
Sorry for the late reply. Torch <= 1.10.0 is recommended since we did not test higher versions. They should probably work if the relevant APIs haven't changed.

**Comment by seanywang0408** [comment]
Thank you for your suggestion. We did not specify the PyTorch version in ``setup.py``. We haved modified the README requirement to a softer one.
