### ISSUE TITLE
What is the default input shape for ConvNext?

### ISSUE THREAD

**Issue by momopusheen** [M3DV/ACSConv#19]
Hi there.

Thanks for your excellent work!

I'm trying to modify the ConvNext in your repo to a feature extraction module. My inputs are 3 slices of grayscale medical images, and I concatenated them to a 3 x 512 x 512 tensor. Thus, my dataloader return data in shape of [batch, 3, 512, 512].

This setting works on normal convnexts. But for your version with ACSConv, as I don't know the shape of the default input, error occurs. So I wonder the size of default input if I want to make use of context info.

My questions are as follows:

- Does it have a shape of [Batch, Channels, Dimension, H, W] ? If not, what should it look like?

If so,

- Should the channel be 1 if my images are in grayscale? 
- Does 'Dimension' means the 3D context of input images?

This question has been bothering me for a long time. Thanks for your consideration!

**Comment by duducheng** [comment]
Hi,

All the models in this repo are 3D models, with input shape of batch_size x channel x depth x height x width. You can follow the readme to use it.

**Comment by momopusheen** [comment]
Thanks for your quick response!

To be honest, I read the readme and tried many times. I wonder that if I could regard the 'depth' as slices of my input. 

As you can see, in most cases, if we want to make use of 3d contexts, the 'depth' won't be a large number. Usually it's 3, 7, or 9. However, if I set 'depth' to 3, error occurs as there are not enough dims for ACSConv to compute. But when 'depth' = 64, it works. 64 is too much for a normal case.

And Should the 'channel' be 1 if my images are in grayscale?

Thanks for your consideration!

**Comment by duducheng** [comment]
> the 'depth' won't be a large number. Usually it's 3, 7, or 9.

I don't think so. Inputs like 32x32x32, 64x64x64 or 128x128x128 are common in the literature. 

> However, if I set 'depth' to 3, error occurs as there are not enough dims for ACSConv to compute.

As for D=3, you should think about the padding. If you use the same padding, it should work. Maybe this repo can be useful if you use large axial-size input, e.g., 3x512x512,
https://github.com/M3DV/AlignShift

> And Should the 'channel' be 1 if my images are in grayscale?

Yes
