### ISSUE TITLE
AdaptiveMaxPooling always returns indices after conversion

### ISSUE THREAD

**Issue by a1302z** [M3DV/ACSConv#20]
Hi, great repository. I've found one issue, that when an AdaptiveMaxPooling layer is converted it will always return the pooling indices afterwards. 

Example code:
```
>>> import torch
>>> from acsconv import converters
The ``converters`` are currently experimental. It may not support operations including (but not limited to) Functions in ``torch.nn.functional`` that involved data dimension
>>> x2 = torch.randn(4,3,128,128)
>>> x3 = torch.randn(4,3,128,128,128)
>>> model2 = torch.nn.Sequential(torch.nn.Conv2d(3, 9, 3), torch.nn.AdaptiveMaxPool2d((32,32)))
>>> model2(x2).shape
torch.Size([4, 9, 32, 32])
>>> converter = converters.ACSConverter
>>> model3 = converter(model2)
>>> model3(x3).shape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'tuple' object has no attribute 'shape'
>>> 
```

The problem is as far as I can see that in [the base converter_file](https://github.com/M3DV/ACSConv/blob/17ecf3a80368980a4e34ccff28a37a4984981d8e/acsconv/converters/base_converter.py#L43C21-L43C21) `_triple_same` converts `return_indices=False` to `return_indices=(False,False,False)`, which is not `False` and by the AdaptiveMaxPool3D interpreted as `True`.

A simple bugfix would be to add `if not isinstance(kwargs[k], bool):` into the for loop over kwargs. I tested it and it seems to solve the problem. I'm happy to provide a pull request if you agree.

**Comment by seanywang0408** [comment]
Great work! Thank you for pointing out. I think this might be resulted from the PyTorch version. By the way, may I ask which version are you using? Another way to fix this bug could be add ``return_indices`` into the list ``['device', 'dtype', 'factory_kwargs']`` (in ``base_converter.py`` L39), which contains the arguments that are not processed by ``_triple_same``. It seems to be a more consistent way to handle the argument.

Please feel free to commit a PR. Thank you for your work again.

**Comment by seanywang0408** [comment]
You are right. The ``return_indices`` argument would be overwrititten by the default value if we don't explicitly pass it to the new module. Your way is the better option. 

By the way, we do specify the PyTorch version to be lower than 1.10.0 due to possible API changes. Yet it is always a bonus to support a higher version. Thank you again for your work :)

**Comment by a1302z** [comment]
I've created the PR. I think the issue can be closed then :)

**Comment by duducheng** [comment]
Thank you for your contributions! @a1302z
