### ISSUE TITLE
typo in eq1

### ISSUE THREAD

**Issue by hubutui** [M3DV/ACSConv#5]
![image](https://user-images.githubusercontent.com/2948593/101322805-97594700-38a2-11eb-9214-bf16315be9ea.png)
I believe you mean `a`, not `v`. 
BTW, is this paper in print in any conference or journal?

**Comment by duducheng** [comment]
Hi,

Thank you for figuring it out!

The paper is still in revision by a journal (available soon). 

You may refer to our arXiv preprint.

Jiancheng

**Comment by hubutui** [comment]
Ok, thanks.
