### ISSUE TITLE
LIDC-IDRI experiment  - doubt

### ISSUE THREAD

**Issue by suresh-s** [M3DV/ACSConv#7]
After training using "python train_segmentation.py", Readme fild doesn't provide evaluation step and running the demo.  I don't know how to evaluate, and how to run the demo?  Could you provide the details?

**Comment by seanywang0408** [comment]
Hi. The evaluation process is also conducted in the "train_segmentation.py" script. It executes evaluation on test-set at the end of each epoch. As for the "demo" you mention, could you please clarify what it means? To my mind, the "train_segmentation.py" and "train_classification.py" scripts are already ready-to-use.

**Comment by suresh-s** [comment]
Thank you for quick reply. I am New to this medical imaging field.   Demo means, i want to use the sample images/videos as input and get the output images/videos, want to visualize the results

**Comment by seanywang0408** [comment]
I'm afraid that we haven't provided a script for this. However, you might separate the test function in the "train_segmentation" script with some modifications on reading and writing data, to support a demo. It shouldn't be too complicated. If you achieve thet, welcome to submit a pull-request to us!
